### ISSUE TITLE
Token colors lacking

### ISSUE THREAD

**Issue by probablyjassin** [shoobah/pinkasheck#3]
Could you improve the colors of tokens? They mostly are all pink, I would like to be able to differentiate types and properties and functions and such. Even just using the VSCode default token colors would be great, thank you.

**Comment by shoobah** [comment]
Oh, I certainly could. I haven't touched this in ages so it would probably need some updates.
I'll get into it when I have some time 😅

Glad to see someone using it!

**Comment by probablyjassin** [comment]
thanks for considering! even if u dont end up doing it, still a great theme i really enjoy!
